apiVersion: v1
kind: Service
metadata:
  name: customerserviceservice
spec:
  type: NodePort
  selector:
    app: customerservice
  ports:
    - protocol: TCP
      nodePort: 30083
      port: 9745
      targetPort: 9745